### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by sleithdylan** [TheCyberCode/TAWDiscord#7]
**Is your feature request related to a problem? Please describe.**
This feature is not related to a problem. 

**Describe the feature/solution you'd like**
I think it would be cool to make the discord bots public and then for anyone that programs, they are able to contribute to the community to help make the discord bots more robust if they love Open Source. ❤️

**Describe alternatives you've considered**
If you don't want to make the discord bots public, then you could get a list of email's from users of TAW Discord and make us as a collaborator.

**Additional context**
None.

**Comment by TheCyberCode** [comment]
I regret to inform you but we will not be making the bots code public or avaliable to anyone in the community. Sorry for any inconvenience.

**Comment by TheCyberCode** [comment]
This is non negotiable.
